name: Labeler

# on:
#   pull_request_target:
#     types:
#       - opened
#       - reopened
#       - edited
#       - synchronize

on:
  pull_request:

jobs:
    pr-labels:
        # Job to assign PR labels
        name: pr-labels
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Assign labels
              uses: actions/labeler@v4
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labels.yml
                  sync-labels: true